### 
# @name CreateNewBook
POST http://localhost:4004/odata/v4/bookshop/Books
Content-Type: application/json

{"title": "TESTINGGG2 Long And Thanks For All The Fish"}



###
# @name BooksQuery
GET http://localhost:4004/odata/v4/bookshop/Books



### @name DeleteOperation
@book_ID = {{ BooksQuery.response.body.value[2].ID }}
GET http://localhost:4004/odata/v4/bookshop/Books({{book_ID}})
###
DELETE http://localhost:4004/odata/v4/bookshop/Books({{book_ID}})



### 
# @name ReadSpecificBookEntity
GET http://localhost:4004/odata/v4/bookshop/Books({{book_ID}})
